pltl/Homework/urls.py
from django.conf.urls import patterns, include, url
from Homework.views import homework_submissions_for_particular_assignment

urlpatterns = patterns('', url(r'^(?P<assignment_id>\w+)/Grade',homework_submissions_for_particular_assignment,name = 'homeworkList')
    )

pltl/User/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from User import views


urlpatterns = patterns('',
    url(r'^$', views.user_signup_save, name = 'user_signup_save'),
    url(r'^home', views.homepage, name = 'homepage'),
    url(r'^login', views.login, name = 'login'),
    url(r'^home/', views.create_class, name= "test"),
    url(r'^Class/', include('Class.urls', namespace= "Class")),
    url(r'^searchclass/', views.search_classes, name= "searchclass"),
    #url(r'^manage/', views.class_student_info, name='class_student_info'),
    url(r'^(?P<class_id>\w+)/manage/', views.class_student_info, name='class_student_info'),
    url(r'^(?P<class_id>\w+)/group_view/', views.group_view, name='group_view'),
    url(r'^updateclass/', views.update_class_details, name= "updateclass"),
    )

pltl/pltl/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from User.views import user_signup_save, login,logout
from django.conf import settings
from django.conf.urls.static import static
from pltl import views
from django.conf.urls import handler404

admin.autodiscover()


urlpatterns = patterns('',
    
   url(r'^$', TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    url(r'^help/', TemplateView.as_view(template_name = 'help.html'), name = 'help'),
    url(r'^contact/', TemplateView.as_view(template_name = 'contact.html'), name = 'contact'),
    url(r'^Class/Assignment/',include('Homework.urls')),
    
    url(r'^signup/', user_signup_save, name="user_signup_save"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'User/', include('User.urls', namespace="User")),
    #url(r'^login/', login, name = "login"),
    url(r'^logout/', logout, name = "logout"),
    #url(r'^User/search_for_class','Class.views.search_for_class', name = "searchForClass"),
    url(r'^Courses/', 'Course.views.course_list', name = "course"),
    url(r'^Classes/', 'Class.views.class_list', name = "class"),
    url(r'^Homework/(?P<ass_id>\w+)$', 'Homework.views.homework_submission', name = "homework_submission"),
    url(r'^Homework/', 'Homework.views.homework_submission', name = "homework_submission"),
    url(r'^PageNotFound/', TemplateView.as_view(template_name = '404.html'), name = '404'),
    url(r'^class/', TemplateView.as_view(template_name = 'class_homepage.html'), name = "class"),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.error404

pltl/Course/models.py
'''This is the Course models'''
from django.db import models

# Create your models here.
'''making our own Course class'''
class Course(models.Model):
	course_id = models.CharField(max_length=20, default = 'DEFAULT VALUE', db_index=True, unique=True, blank=False)
	course_name = models.CharField(max_length=200, blank=False)
	
	def __unicode__(self):
		return self.course_id
def allCourses():
	course_info = Course.objects.all()
	return course_info

pltl/Homework/models.py
from django.db import models
from Assignment.models import Assignment
from User.models import User
from datetime import datetime
from time import time

def get_upload_file_name(instance, filename):
	return "homework/%s_%s" % (str(time()).replace('.','_'), filename)

class Homework(models.Model):
	homework_id = models.AutoField(primary_key=True)
	assignment_id = models.ForeignKey(Assignment, to_field = 'assignment_id')
	homework_soln = models.FileField(upload_to=get_upload_file_name)
	submitted_by = models.EmailField(max_length=20, blank = False)
	submitted_timestamp = models.DateTimeField(auto_now_add=True, blank=True)
	grade = models.CharField(max_length = 3, blank = True, null=True)
	feedback = models.CharField(max_length = 300, blank = True, null=True)
	graded_by = models.CharField(max_length = 50, blank = True, null=True)

pltl/Course/forms.py
from django.forms import ModelForm
from Course.models import Course


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['course_id', 'course_name']

pltl/Homework/forms.py
from django.forms import ModelForm
from django.forms import ModelChoiceField
from Homework.models import Homework
from Assignment.models import Assignment
from User.models import User
from django import forms


class HomeworkForm(ModelForm):
    class Meta:
        model = Homework
        fields = ['homework_soln']

pltl/Course/views.py
from django.shortcuts import render, render_to_response, RequestContext
from django.template import RequestContext
from Course.forms import CourseForm
from django.http import HttpResponseRedirect
from Course.models import Course


def course_list(request):
	course_info = Course.objects.all()
	if request.method == 'POST':
		form = CourseForm(request.POST)
		if form.is_valid():
			new_course = form.save(commit=False)
			new_course = form.save()
	else:
		form = CourseForm()

	return render_to_response('courses.html',{'courses': course_info, 'form': form},context_instance=RequestContext(request))

pltl/Homework/views.py
from django.shortcuts import render, render_to_response, RequestContext
from django.template import RequestContext
from Homework.forms import HomeworkForm
from django.http import HttpResponseRedirect, HttpResponse
from Homework.models import Homework
from Assignment.models import Assignment
from Enrolled_Class.models import Enrolled_Class
from User.models import User
from django.contrib import auth
from datetime import datetime
from django.core.urlresolvers import reverse
import json

def homework_submission(request, ass_id):
    email = request.session['_auth_user_id']
    cl_id = Assignment.objects.filter(assignment_id = ass_id).values('class_id')
    class_id = cl_id[0]['class_id']
    enrolled_by = Enrolled_Class.objects.filter(email = email, class_id = class_id, role = 'Student', status = 'Enrolled').values('email')
    if enrolled_by:
        assignment_id = Assignment.objects.get(assignment_id = ass_id)
        ass_info = Assignment.objects.filter(assignment_id = ass_id)
        user_email = User.objects.get(email = email)
        ass_name = ""
        for ass in ass_info:
            index = ass.assignmentfile.name.rfind('_')
            ass_name = ass.assignmentfile.name[index+1:]

        if request.method == 'POST':
            form = HomeworkForm(request.POST, request.FILES)
            if form.is_valid():
                new_home = form.save(commit=False)
                new_home.assignment_id = assignment_id
                new_home.submitted_by = user_email 
                new_home.save()
            return HttpResponseRedirect(reverse('homework_submission',kwargs={'ass_id': ass_id}))
        else:
            form = HomeworkForm()

        homework_info = Homework.objects.filter(assignment_id = assignment_id, submitted_by = user_email)
        homework_name = ""
        if homework_info:
            for home in homework_info:
                index = home.homework_soln.name.rfind('_')
                homework_name = home.homework_soln.name[index+1:]
        return render_to_response('homework.html',{'ass_info': ass_info, 'ass_name': ass_name, 'form': form , 'homework_info' : homework_info, 'homework_name' : homework_name, 'ass_id': ass_id},context_instance=RequestContext(request))
    else:
        return render_to_response('404.html')

def homework_submissions_for_particular_assignment(request,assignment_id):
    role = instructor_or_leader(request,assignment_id)
    if role == 'Instructor':
        submittedHomeworks = Homework.objects.filter(assignment_id = assignment_id)
    else:
        submittedHomeworks = []
        leaderEnrolledClass= Enrolled_Class.objects.get(class_id = Assignment.objects.get(assignment_id = assignment_id).class_id,
                                                                                          email = request.session['_auth_user_id'] )
        for student in leaderEnrolledClass.students_led.all():
            if Homework.objects.filter(assignment_id = assignment_id, submitted_by = student.email).exists():
            
                submittedHomeworks.append(Homework.objects.get(assignment_id = assignment_id, submitted_by = student.email))
    
    assignment_name = Assignment.objects.get(assignment_id = assignment_id).assignment_name
    students = {}
    for submission in submittedHomeworks:
        
        students[submission.submitted_by] = {}
        students[submission.submitted_by]['email'] = submission.submitted_by
        students[submission.submitted_by]['name']  = User.objects.get(email = submission.submitted_by).get_full_name()
        students[submission.submitted_by]['grade'] = submission.grade
        students[submission.submitted_by]['homework_soln'] = submission.homework_soln.url
        
        students[submission.submitted_by]['feedback'] = submission.feedback
        students[submission.submitted_by]['graded_by'] = submission.graded_by
    
    if request.POST:
        return submit_grade(request,students,assignment_id,role)
    
    return render(request,'gradeAssignment.html', {'students' : students, 'assignment_id' : assignment_id,
                                                   'assignment_name' : assignment_name,'role':role } )

def submit_grade(request, students,assignment_id,role):

    email = request.POST.get('email')
    grade = request.POST.get('Grade')
    feedback = request.POST.get('Feedback')
    
    homework = Homework.objects.get(assignment_id=assignment_id, submitted_by = email)
    homework.grade = grade
    homework.feedback = feedback 
    homework.graded_by = role
    homework.save()
    
    #Since grades and feedback have already been retrieved, update to reflect the changes.
    students[email]['grade'] = grade
    students[email]['feedback'] = feedback


    return HttpResponse(json.dumps(students),content_type = 'application/json')

def instructor_or_leader(request,assignment_id):
    emailOfGrader = request.session['_auth_user_id']
    grader = Enrolled_Class.objects.get(class_id = Assignment.objects.get(assignment_id = assignment_id).class_id , email = emailOfGrader)
    if grader.role == 'Instructor':
        return 'Instructor'
    else:
        return 'Peer Leader'

pltl/templates/class_homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content%}
	<head>
		<meta charset="utf-8">
		<title>Upload Assignment</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static "css/foundation.css" %}"></link>
		<link rel="stylesheet" href="{% static "css/foundation-datepicker.css" %}"></link>
		<link rel="stylesheet" href="{% static "css/font-awesome.css" %}"></link>
		<link rel="stylesheet" href="{% static "css/assignment.css" %}"></link>
		<link rel="stylesheet" href="{% static "css/ui.css" %}"></link>
		<script src="{% static "js/vendor/modernizr.js" %}"></script>
		<script src="{% static "js/vendor/jquery.js" %}"></script>
		<script src="{% static "js/foundation/foundation-datepicker.js" %}"></script>
		<script src="{% static "js/Assignment.js" %}"></script>
	</head>

	<body id='assignmentSection'>
		<div class="row">
			Header Image
		</div>
		<div class="row">
			<dl class="nice contained tabs">
			  <dd><a href="#Assignments" class="active">Assignments</a></dd>
			  <dd><a href="#Students">Students</a></dd>
			  <dd><a href="#Bulletin">Bulletin</a></dd>
			  
			</dl>

			<ul class="nice tabs-content contained">
			  <li class="active" id="classTab">Classes tab</li>
			  <li id="coursesTab">Cources Tab</li>
			  <li id="uploadAssignmentTab">
							<div   class="row">
								<section class="large-2 columns">
									<dl class="nice vertical tabs">
									  <dd><a href="#vertical1" class="active">Course 1</a></dd>
									  <dd><a href="#vertical2">Course 2</a></dd>
									  <dd><a href="#vertical3">Course 3</a></dd>
									</dl>
								</section>		
								<section class="large-10 columns">
									<!-- Upload form. Note enctype attribute! -->
									<form action="{% url 'User:Assignment:list' %}" method="post" enctype="multipart/form-data">
										{% csrf_token %}
										<div class="large-6 row">
													<div class="large-4 columns">
													  <label>Assignment ID:</label>
													</div>
													<div class="large-6 columns name-field" >
													  <label>{{ form.assignment_id}}</label>
													</div>
													
										</div>
										<div class="large-6 row">
													<div class="large-4 columns" >
													  <label>Course ID:</label>
													</div>
													<div class="large-6 columns name-field" >
													  <label>{{ form.course_id}}</label>
													</div>
										</div>
										<div class="large-6 row">
													<div class="large-4 columns" >
													  <label>Publish Date:</label>
													</div>
													<div class="large-6 columns name-field">
													  <label>{{ form.pub_date}}</label>
													</div>
										</div>
										<div class="large-6 row">
													<div class="large-4 columns" >
													  <label>Due Date:</label>
													</div>
													<div class="large-6 columns name-field" >
													  <label>{{ form.due_date}}</label>
													</div>
										</div>
										<div class="large-6 row">
													<div class="large-4 columns" >
													  <label>Total Grade:</label>
													</div>
													<div class="large-6 columns name-field" >
													  <label>{{ form.total_grade}}</label>
													</div>
										</div>
										<div class="large-6 row">
													<div class="large-4 columns" >
													  <label>Assignment files:</label>
													</div>
													<div class="large-6 columns name-field">
													  <label>{{ form.assignmentfile}}</label>
													</div>
										</div>
										
										<p><input type="submit" value="Upload" /></p>
									</form>
								</section>
						</div>
			  </li>
			  <li id="assignmentListTab">
					Assignment List
			  </li>
			</ul>
		</div>			
	</body>
{% endblock %}

pltl/templates/courses.html
<!doctype html>
<html class="no-js" lang="en">
  	<head>
    	<meta charset="utf-8" />
    	<title>PLTL | Courses</title>
  	</head>
  	<body>
        <p>
          {% if courses %}
            <h1>Courses :</h1>
            {% for course in courses %}
              <h3>{{ course.course_id }} : {{ course.course_name }}</h3>
            {% endfor %} 
          {% else %}
            <h3>No Courses to Display</h3>
          {% endif %}         
        </p>
      <h1>Create New Course</h1>
        <form method = 'POST' action = "{% url "course" %}"> {% csrf_token %}
          <p>{{ form.as_p }}</p>
          <input type = 'submit' value="Add New Course"> 
        </form>
  	</body>
</html>

pltl/templates/createAssignment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block linkscript %}
<link rel="stylesheet" href="{% static "css/assignment.css" %}"></link>
<link rel="stylesheet" href="{% static "css/ui.css" %}"></link>
<script>
   var class_id = "\{{classid}}";
   function redirect() {
           
   	window.location = "/User/Class/"+class_id
   
   }
</script>
{% endblock %}
{% block username %}Welcome {{request.user.fname}}{% endblock %}
{% block logout %}    
{%if user.is_authenticated%}
<li><a href = " {% url 'logout'%}"><strong> logout</strong></a></li>
{%endif%}
{% endblock %}
{% block content %}
<div class="row">
   <div id="classHomeTitle">
      Class : {{classid}}    
   </div>
   <section id= "formSection" class="large-10 columns">
      <!-- Upload form. Note enctype attribute! 
         action="{% url 'User:Class:uploadAssignment' %}{{classid}}"  -->
      <form action="" method="post" enctype="multipart/form-data">
         {% csrf_token %}
         <input type="hidden" name="classid" value="{{classid}}">
         <div class="row">
            <div class="large-4 columns">
               <label>Assignment Name:</label>
            </div>
            <div class="large-2 columns name-field" >
               {{ form.assignment_name }}
            </div>
         </div>
         <div class="row">
            <div class="large-4 columns" >
               <label>Publish Date:</label>
            </div>
            <div class="large-2 columns name-field">
               {{ form.pub_date }}
            </div>
         </div>
         <div class="row">
            <div class="large-4 columns" >
               <label>Due Date:</label>
            </div>
            <div class="large-2 columns name-field" >
               {{ form.due_date }}                       
            </div>
         </div>
         <div class="row">
            <div class="large-4 columns" >
               <label>Total Grade:</label>
            </div>
            <div class="large-2 columns name-field" >
               {{ form.total_grade }}                       
            </div>
         </div>
         <div class="row">
            <div class="large-4 columns" >
               <label>Assignment files:</label>
            </div>
            <div class="large-3 columns name-field">
               {{ form.assignmentfile }}
            </div>
         </div>
         <div id="createButtons">
            <p><input id="create" type="submit" value="Upload" class="radius button success medium" />
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               <button type="button" class="radius button secondary medium" onclick = redirect();> Cancel </button> 
            </p>
         </div>
      </form>
   </section>
</div>
{% endblock %}

pltl/templates/group_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" href="{% static "css/ui.css" %}"></link>
    <script src="{% static "js/Assignment.js" %}"></script>
{% endblock %}
{% block username %}Welcome {{request.user.fname}}{% endblock %}
{% block logout %}    
{%if user.is_authenticated%}
    <li><a href = "/User/home"><strong>Home</strong></a></li>
    <li><a href = " {% url 'logout'%}"><strong> logout</strong></a></li>
{%endif%}
{% endblock %}
{% block content %}
<title>PLTL | {{ class_id }} | Group View</title>      
<div align="left">
<form data-abide action="{% url "User:class_student_info" class_id %}">
{% csrf_token %}
<input type='submit' class="radius button default medium" id="btnNew" value="Back">
</div>
</form>

<div align="center">
<h3>Group View: {{ class_id }}</h3>
</div>

{% if group_view %}
<h4>
<div align="center">
<dl>
    {% for leader, students_led in group_view.items %}
        <dt><u>{{ leader.get_full_name }}</u></dt>
        {% for student in students_led %}
            <dd>{{ student.get_full_name }}</dd>
        {% endfor %}
    {% endfor %}
</dl>
</div>
</h4>
{% endif %}
{% endblock %}

pltl/templates/homework.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} PLTL | Homework Submission{% endblock %}
{% block linkscript %}
    <link rel="stylesheet" href="{% static "css/ui.css" %}"></link>
    <script src="{% static "js/Assignment.js" %}"></script>
{% endblock %}
{% block username %}Welcome {{request.user.fname}}{% endblock %}
{% block logout %}    
{%if user.is_authenticated%}
    <li><a href = "/User/home"><strong>Home</strong></a></li>
    <li><a href = " {% url 'logout'%}"><strong> logout</strong></a></li>
{%endif%}
{% endblock %}
{% block content %}
<title>PLTL | Homework Submission </title>
<ul class="nice tabs-content contained">
  <div class="row">
    <table>
      {% if ass_info %}
        <p>
        {% for ass in ass_info %}
               <font size="5">{{ ass.assignment_name }} :</font><br>   
               <tr>
                <td>
                  Click to view : 
                 </td>
                  {% if ass.assignmentfile %} 
                    <td>
                        <a target=\"_blank\" href="{{ ass.assignmentfile.url}}" title=\"\">{{ ass_name }}</a>
                    </td>
                  {% else %}
                    <td>
                        No Assignment Uploaded
                    </td>
                  {% endif %}
                </tr>
                <tr>
                  <td>
                  Uploaded On :  
                </td>  
                <td>
                   {{ ass.pub_date}} 
                </td>               
                </tr>
                <tr>
                  <td>
                    <font color="red">Due Date : </font> 
                  </td>
                  <td>
                    <font color="red">{{ ass.due_date}}</font> 
                  </td>
                </tr>
                <tr>
                  <td>
                  Total Grade : 
                </td>
                 <td>
                  {{ ass.total_grade}}
                </td>
                </tr> 
          </table>
        {% endfor %}

        {% if not homework_info %}
        <div class="large-12 row">
          <div class="large-3 columns" >
          <form data-abide method = 'POST' action = "{% url "homework_submission" %}{{ ass_id }}" enctype="multipart/form-data"> {% csrf_token %}
            <label for="homework_soln">Select a file : </label>
            <input id="homework_soln" type="file" name="homework_soln" required>
            <small class="error">Please select a file</small>
            <input type = 'submit' class="radius button success medium" value="Upload Homework"> 
          </form>
          </div>
        </div>
        </p>
        {% endif %}
      {% endif %}
    
        <br>
        <p>
          <font size="5">Submitted homework :</font><br>
          <table>
            {% if homework_info %}
            <tr>
                  <th style='width:200px'>Submitted Homework </th>
                  <th style='width:200px'>Submitted On </th>
                  <th style='width:200px'>Grade</th>
                  <th style='width:200px'>Feedback</th>
            </tr>
              {% for homework in homework_info %}
              <tr>   
                  <td>       
                    <a target=\"_blank\" href="{{ homework.homework_soln.url}}" title=\"\">{{ homework_name }}</a>
                  </td>
                  <td>
                    {{ homework.submitted_timestamp}}
                  </td>
                  <td>
                      {{ homework.grade }}
                  </td>
                  <td>
                      {{ homework.feedback }}
                  </td>
              </tr> 
              {% endfor %}
            {% else %}
            <tr>
              <td>
                Nothing to display. No homeworks submitted yet
              </td>
            </tr>
            {% endif %}
          </table>
        </p>
  </div>
</ul>
{% endblock %}

pltl/templates/index.html
{% extends 'base.html' %}
{% block logout %}    
{%if user.is_authenticated%}
    <li><a href = "/User/home"><strong>Home</strong></a></li>
    <li><a href = " {% url 'logout'%}"><strong> logout</strong></a></li>
{%endif%}
{% endblock %}
{% load staticfiles %}
<title>PLTL | Welcome </title>      
{% block content %}

    <div class="row">
      <div class="large-12 columns">
        <div class="row">
          <div class="small-12 large-12 columns">&nbsp;</div>
        </div>
      
        <div class="row">
          <div class="large-12 columns">        
            <div class="panel">
              <div class="large-6 columns">
                <h4>Welcome to Peer Led Team Learning!</h4>
              </div>
              {%if not user.is_authenticated%}
              <div class="large-6 columns">
                <div class="large-8 columns">
                  <a href="#" class="radius button small right" data-reveal-id="LoginModal" id="loginButton"><strong>Login</strong></a>

                  <div id="LoginModal" class="reveal-modal" data-reveal>
                    <form data-abide onsubmit="return false;" id="login">
                      {% csrf_token%}
                      <h4>Log In</h4>
                      <hr/>

                      <div class="row">
                        <div class="large-12 columns" class="email-field">
                          <label>Email:
                            <input id="emailInput" name="email" type="email" value = "mgross@email.com"required/>
                          </label>
                          <small class="error">Email is required and must be in a valid format</small>
                        </div>
                      </div>

                      <div class="row">
                        <div class="large-12 columns" class="name-field">
                          <label>Password:
                            <input name="password" id='passwordInput'type="password" value='goat' required/>
                          </label>
                          <small class="error">Please enter password</small>
                        </div>
                      </div>

                      <div class="row">
                        <input id="cbRemember" type="checkbox" checked></input><label for="cbRemember">Remember me</label>
                      </div>

                      <div class="row">
                        <div class="large-9 columns">
                          <ul class="inline-list left">
                            <!--<li><a href="#">Forgot your password?</a></li>-->
                          </ul>
                        </div>
                      </div>
                      <div data-alert class="alert-box alert round" id="loginError" style="visibility:hidden">
                        Email or password is incorrect
                      </div>
                      <div class="row">  
                        <div class="large-12 columns">
                          <button class="radius button success small right" id="submitLogin" onclick=login()><strong>Login</strong></a>  
                        </div>  
                      </div>                    
                    <a class="close-reveal-modal">&#215;</a>
                  </form>
                </div>
              </div>


              <div class="large-4 columns">
                <a href="#" class="radius button small right" data-reveal-id="SignUpModal" id="signUpButton"><strong>Sign Up</strong></a>

                  <div id="SignUpModal" class="reveal-modal2" data-reveal>

                        <div align="center"><h2>Create an Account</h2></div>
                        <hr/>
                        <div class="medium-6 medium-centered large-centered large-6 columns">
                          <form data-abide action = "{% url 'User:user_signup_save' %}" method="POST">
                            {%csrf_token%}
                            <div class="name-field">
                              <label>First Name</label>
                              <input name="fname"type="text" required></input>
                              <small class="error" data-error-message="">A first and last name is required.</small>
                            </div>
                            <div class="name-field">
                              <label>Last Name</label>
                              <input name="lname"type="text" required></input>
                              <small class="error" data-error-message="">A first and last name is required.</small>
                            </div>
                            <div class="email-field">
                              <label>Email</label>
                              <input name="email" type="email" placeholder="example@dot.com" required></input>
                              <small class="error">An email address is required.</small>
                            </div>
                            <div class="password">
                              <label for="password">Password</label>
                              <input id="password" type="password" required="" name="password"></input>
                              <small class="error"></small>
                            </div>
                            <div class="password2">
                              <label for="confirmPassword">Confirm Password</label>
                              <input id="confirmPassword" type="password" data-equalto="password" required="" name="confirmPassword" data-invalid=""></input>
                              <small class="error" data-error-message="">Passwords must match.</small>
                            </div>
                            <div class="terms">
                              <label><small>By creating an account you have read and agree to the <a href="#">terms and conditions</a>.</small></label>
                              <input id="checkbox1" type="checkbox" checked required></input><label for="checkbox1">I Agree</label>
                              <small class="error">You must agree to the terms and conditions.</small>
                            </div>
                            <br />
                            <br />         
                            <button class="radius button submit small" ><strong>Sign Up</strong></button>
                            <br />
                            <!--<small>Sign in with <a href="#">Facebook</a>, <a href="#">Google</a>, or <a href="#">Twitter</a>.</small>-->
                          </form>
                        </div>
                
                    <a class="close-reveal-modal">&#215;</a>
                </div>
              </div>
            </div>
            
            <div class="row">
          </div>
        </div>          
      </div>
    </div>
     {%endif%}
    <div class="row">
      <div class="large-12 columns">
        <div id="slider">
          <img src="{% static "img/Image1.png" %}">
        </div>          
        <hr/>
      </div>
    </div>
       
    <div class="row">
      <div class="large-3 columns">
        <h4></h4>
        <p>Peer Led Team Learning is designed to connect Students, Peer Leaders and Instructors so every student can get the help they need when they need it.</p>
      </div>
        
      <div class="large-3 columns">
        <h4></h4>
        <p>It impoverishes the learning environment if students don't talk to other students. Peer Led Team Learning makes it very easy to get a discussion going.</p>
      </div>
        
      <div class="large-6 columns">
        <h4></h4>
        <p><li>Wiki style format enables collaboration in a single space.</li></p>
        <p><li>Instructors endorse answers to keep the class on track.</li></p>
        <p><li>Questions and posts needing immediate action are highlighted.</li></p>
        <p><li>Anonymous posting encourages every student to participate.</li></p>
        <p><li>Highly customizable online polls.</li></p>
      </div>
    </div>
<script type = "text/javascript"> 
  function login(){
    $.ajax({
      type : "POST",
      url  : "http://localhost:8000/User/login",
      dataType : "json",
      async : true,
      data : {
        csrfmiddlewaretoken : '{{ csrf_token }}',
        email : $('#emailInput').val(),
        password: $('#passwordInput').val()

      },
        
      success:function(response){
        if(response.success){ 
          window.location.href = '/User/home';
        }
        else $('#loginError').css("visibility", "visible");        
      },
      /**
      failure:function(){
        console.log("failed");
      },
      error:function(){
        console.log("failed");
      }*/

    });

  }   
</script>
{% endblock %}